services:

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus-container
    volumes:
      - ./metrics/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always
    network_mode: host
  web:
    build: .
    ports:
      - "8080:8080"
  grafana:
    image: grafana/grafana-oss:8.5.2
    network_mode: host
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./metrics/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Grafana
      - GF_SERVER_DOMAIN=localhost
    user: "1000"
    ports:
      - 3000:3000