pipeline {
    agent none
    environment {
        GIT_SSL_NO_VERIFY = 'true'
    }
    stages {
        stage('Clone Code') {
            agent {
                label 'master'
            }
            steps {
                echo "1.Git Clone Code"
                sh 'curl "http://p2.nju.edu.cn/portal_io/login?username=usm&password=pwd"'
                git branch: "main", url: "https://github.com/liukedian/yuanshen"
            }
        }
        stage('Image Build') {
            agent {
                label 'master'
            }
            steps {
                echo "2.Image Build Stage"
                sh 'docker build -f Dockerfile -t msg:${BUILD_ID} . '
                sh 'docker tag msg:${BUILD_ID} harbor.edu.cn/nju34/msg:${BUILD_ID}'
            }
        }
        stage('Push') {
            agent {
                label 'master'
            }
            steps {
                echo "3.Push Docker Image Stage"
                sh "docker login --username=nju34 harbor.edu.cn -p nju342023"
                sh "docker push harbor.edu.cn/nju34/msg:${BUILD_ID}"
            }
        }
    }
}


node('slave') {
    container('jnlp-kubectl') {

        stage('Clone YAML') {
            echo "4. Git Clone YAML To Slave"
//            sh 'export GIT_SSL_NO_VERIFY=true'
            sh 'curl "http://p2.nju.edu.cn/portal_io/login?username=usm&password=pwd"'
            git branch: "main", url: "https://github.com/liukedian/yuanshen"
        }
        stage('Pull Image') {
            sh "docker login --username=nju34 harbor.edu.cn -p nju342023"
            sh "docker pull harbor.edu.cn/nju34/msg:${BUILD_ID}"
        }

        stage('YAML') {
            echo "5. Change YAML File Stage"
            sh 'sed -i "s/VERSION/${BUILD_ID}/g" ./k8s/msg.yaml'
        }

        stage('Deploy') {
            echo "7. Deploy To K8s Stage"
            sh 'kubectl apply -f ./k8s/msg.yaml --namespace=nju34'
        }
    }
}
